# Generated by Django 4.2.2 on 2023-06-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('imag', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('purchase_price', models.IntegerField(default=0, verbose_name='Цена за покупку')),
                ('date_of_creation', models.DateField(default='20-06-2023', verbose_name='Дата создания')),
                ('last_modified_date', models.DateField(default='20-06-2023', verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
