# Generated by Django 4.2.2 on 2023-06-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_categoryadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
