# Generated by Django 4.2.2 on 2023-06-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_products_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
    ]
