# Generated by Django 4.2.2 on 2023-06-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_products_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAdmin',
        ),
    ]
